/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.2.1.1                                               */
/*  Date (dd.mm.yyyy):  7. 4.2023   Time (hh:mm): 10:38                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

#if !defined(GX_UTF8_SUPPORT)
#error "The symbol GX_UTF8_SUPPORT must be defined to support the Studio project settings".
#endif

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 800
#define DISPLAY_1_Y_RESOLUTION 480
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_CHINESE 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_NEW_COLOR_D6D5B7 29
#define GX_COLOR_ID_NEW_BEEDC7 30
#define DISPLAY_1_COLOR_TABLE_SIZE 31

/* Font ID definitions                                                         */

#define GX_FONT_ID_MASHANZHENG24 4
#define GX_FONT_ID_MASHANZHENG16 5
#define DISPLAY_1_FONT_TABLE_SIZE 6

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_CV____85______ 5
#define GX_PIXELMAP_ID_EIS____85______ 6
#define GX_PIXELMAP_ID_FIT_BO_250 7
#define GX_PIXELMAP_ID_FIT_BO_480 8
#define GX_PIXELMAP_ID_FIT_NY_250 9
#define GX_PIXELMAP_ID_FIT_NY_480 10
#define GX_PIXELMAP_ID_FIT_ZRI_250 11
#define GX_PIXELMAP_ID_FIT_ZRI_480 12
#define GX_PIXELMAP_ID_FOLDER____85_______48_ 13
#define GX_PIXELMAP_ID_ICONS8_BACK_ARROW_64 14
#define GX_PIXELMAP_ID_LOCK_____1 15
#define GX_PIXELMAP_ID_LOGO200 16
#define GX_PIXELMAP_ID_LOGO400__ 17
#define GX_PIXELMAP_ID_ORIG_BO_250 18
#define GX_PIXELMAP_ID_ORIG_BO_480 19
#define GX_PIXELMAP_ID_ORIG_NY_250 20
#define GX_PIXELMAP_ID_ORIG_NY_480 21
#define GX_PIXELMAP_ID_ORIG_ZRI_250 22
#define GX_PIXELMAP_ID_ORIG_ZRI_480 23
#define GX_PIXELMAP_ID_REGLOGO800480____1 24
#define GX_PIXELMAP_ID_SETTING_____85______ 25
#define GX_PIXELMAP_ID_SM_BO_250 26
#define GX_PIXELMAP_ID_SM_BO_480 27
#define GX_PIXELMAP_ID_SM_NY_250 28
#define GX_PIXELMAP_ID_SM_NY_480 29
#define GX_PIXELMAP_ID_SM_ZRI_250 30
#define GX_PIXELMAP_ID_SM_ZRI_480 31
#define GX_PIXELMAP_ID__00X480___ 32
#define GX_PIXELMAP_ID_SINE_1 33
#define GX_PIXELMAP_ID_TRIANGULAR_1 34
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 35

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define GX_STRING_ID_STRING_12 12
#define GX_STRING_ID_STRING_13 13
#define GX_STRING_ID_STRING_14 14
#define GX_STRING_ID_STRING_15 15
#define GX_STRING_ID_STRING_16 16
#define GX_STRING_ID_STRING_17 17
#define GX_STRING_ID_STRING_18 18
#define GX_STRING_ID_STRING_19 19
#define GX_STRING_ID_STRING_20 20
#define GX_STRING_ID_STRING_21 21
#define GX_STRING_ID_STRING_22 22
#define GX_STRING_ID_STRING_23 23
#define GX_STRING_ID_STRING_24 24
#define GX_STRING_ID_STRING_25 25
#define GX_STRING_ID_STRING_26 26
#define GX_STRING_ID_STRING_27 27
#define GX_STRING_ID_STRING_28 28
#define GX_STRING_ID_STRING_29 29
#define GX_STRING_ID_STRING_30 30
#define GX_STRING_ID_STRING_31 31
#define GX_STRING_ID_STRING_32 32
#define GX_STRING_ID_STRING_33 33
#define GX_STRING_ID_STRING_34 34
#define GX_STRING_ID_STRING_35 35
#define GX_STRING_ID_STRING_36 36
#define GX_STRING_ID_STRING_37 37
#define GX_STRING_ID_STRING_38 38
#define GX_STRING_ID_STRING_39 39
#define GX_STRING_ID_STRING_40 40
#define GX_STRING_ID_STRING_41 41
#define GX_STRING_ID_STRING_42 42
#define GX_STRING_ID_STRING_43 43
#define GX_STRING_ID_STRING_44 44
#define GX_STRING_ID_STRING_45 45
#define GX_STRING_ID_STRING_46 46
#define GX_STRING_ID_STRING_47 47
#define GX_STRING_ID_STRING_48 48
#define GX_STRING_ID_STRING_49 49
#define GX_STRING_ID_STRING_50 50
#define GX_STRING_ID_STRING_51 51
#define GX_STRING_ID_STRING_52 52
#define GX_STRING_ID_STRING_53 53
#define GX_STRING_ID_STRING_54 54
#define GX_STRING_ID_STRING_55 55
#define GX_STRING_ID_STRING_56 56
#define GX_STRING_ID_STRING_57 57
#define GX_STRING_ID_STRING_58 58
#define GX_STRING_ID_STRING_59 59
#define GX_STRING_ID_STRING_60 60
#define GX_STRING_ID_STRING_61 61
#define GX_STRING_ID_STRING_62 62
#define GX_STRING_ID_STRING_63 63
#define GX_STRING_ID_STRING_64 64
#define GX_STRING_ID_STRING_65 65
#define GX_STRING_ID_STRING_66 66
#define GX_STRING_ID_STRING_67 67
#define GX_STRING_ID_STRING_68 68
#define GX_STRING_ID_STRING_69 69
#define GX_STRING_ID_STRING_70 70
#define GX_STRING_ID_STRING_71 71
#define GX_STRING_ID_STRING_72 72
#define GX_STRING_ID_STRING_73 73
#define GX_STRING_ID_STRING_74 74
#define GX_STRING_ID_STRING_75 75
#define GX_STRING_ID_STRING_76 76
#define GX_STRING_ID_STRING_77 77
#define GX_STRING_ID_STRING_78 78
#define GX_STRING_ID_STRING_79 79
#define GX_STRING_ID_STRING_80 80
#define GX_STRING_ID_STRING_81 81
#define GX_STRING_ID_STRING_82 82
#define GX_STRING_ID_STRING_83 83
#define GX_STRING_ID_STRING_84 84
#define GX_STRING_ID_STRING_85 85
#define GX_STRING_ID_STRING_86 86
#define GX_STRING_ID_STRING_87 87
#define GX_STRING_ID_STRING_88 88
#define GX_STRING_ID_STRING_89 89
#define GX_STRING_ID_STRING_90 90
#define GX_STRING_ID_STRING_91 91
#define GX_STRING_ID_STRING_92 92
#define GX_STRING_ID_STRING_93 93
#define GX_STRING_ID_STRING_94 94
#define GX_STRING_ID_STRING_95 95
#define GX_STRING_ID_STRING_96 96
#define GX_STRING_ID_STRING_97 97
#define DISPLAY_1_STRING_TABLE_SIZE 98

#endif                                       /* sentry                         */
